apiVersion: v1
kind: Service
metadata:
  name: devops-java-app-p2-enhanced-svc
spec:
  type: LoadBalancer
  selector:
    app: devops-java-app-p2-enhanced
  ports:
    - port: 80        # ELB will listen on 80
      targetPort: 8080  # Pods still on 8080
      protocol: TCP
