apiVersion: v1
kind: Service
metadata:
  name: devops-java-app-p2-enhanced-svc
spec:
  selector:
    app: devops-java-app-p2-enhanced
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 8080  # Pod port inside your container
