apiVersion: v1
kind: Service
metadata:
  name: devops-java-app-p2-enhanced-svc
spec:
  type: LoadBalancer
  selector:
    app: devops-java-app-p2-enhanced
  ports:
    - port: 8080
      targetPort: 8080
